#!/usr/bin/php
<?php
    /*---------------------------------------
    | Bootstrap
    |----------------------------------------
    |
    | We include the bootstrap file to get all the necessary stuff we need.
    | Like the class loader and the helper functions.
    |
    */

    require(__DIR__."/bootstrap/bootstrap.php");

    /*---------------------------------------
    | Run Framys CLI Application
    |----------------------------------------
    |
    | When we run the CLI Application, the current CLI command will be
    | executed in this console and the response sent back to a terminal.
    |
    */

    $input = new \app\framework\Component\Console\ArgvInput();
    $CLI = new \app\framework\Component\Console\Kernel($input);
    var_dump($CLI);